### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jschpinto** [tomstewart89/Vector#2]
Hi tomstewart89. First and foremost, thanks for sharing your code, however, it produces an error when compiling to the Arduino board.

![image](https://user-images.githubusercontent.com/44210995/50589631-50c16d80-0e7f-11e9-99c5-2ab1a92405de.png)

At first, I was integrating your library in my code and it was not working, hence I thought it something I was doing wrong. Be as it may, testing your basic usage example results in the same error. 
Could you possibly provide any help?

Yours sincerely,
jschpinto

**Comment by tomstewart89** [comment]
Hi @jschpinto, sorry for the delayed response. When I first wrote this library the arduino core didn't define operators for new[] and delete[], so I just added them myself at the top of `Vector.h`. Since then it looks they've been added to the core so the compiler is finding multiple definitions.

I've removed my local definitions for those operators so if you check out the latest version of the library you should be good to go. Let me know if you have any problems!
